import os

from dotenv import load_dotenv

load_dotenv()

workday_data = [
    {
        "name": "Capital One Financial",
        "url": os.getenv("CAPITAL_ONE_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Mitsubishi Bank",
        "url": os.getenv("MUFG_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "TD Bank",
        "url": os.getenv("TD_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Bank of America",
        "url": os.getenv("BANK_AMERICA_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Wells Fargo",
        "url": os.getenv("WELLS_FARGO_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Synchrony",
        "url": os.getenv("SYNCHRONY_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Freddie Mac",
        "url": os.getenv("FREDDIE_MAC_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "T Rowe",
        "url": os.getenv("TROWE_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "PWC",
        "url": os.getenv("PWC_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Mastercard",
        "url": os.getenv("MASTERCARD_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "G Research",
        "url": os.getenv("G_RESEARCH_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Wellington",
        "url": os.getenv("WELLINGTON_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Russell Investments",
        "url": os.getenv("RUSSELL_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("RUSSELL_PASSWORD"),
    },
    {
        "name": "Mizuho",
        "url": os.getenv("MIZUHO_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Gartner",
        "url": os.getenv("GARTNER_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Northern Trust",
        "url": os.getenv("NORTHERN_TRUST_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Santander",
        "url": os.getenv("SANTANDER_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "PNC Bank",
        "url": os.getenv("PNC_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "US Bank",
        "url": os.getenv("US_BANK_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Citibank",
        "url": os.getenv("CITIBANK_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Pitney Bowes",
        "url": os.getenv("PITNEY_BOWES_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Deutsche Bank",
        "url": os.getenv("DB_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "RBS",
        "url": os.getenv("RBS_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Apple Bank",
        "url": os.getenv("APPLE_BANK_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Franklin Investments",
        "url": os.getenv("FRANKLIN_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Barclays",
        "url": os.getenv("BARCLAYS_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "General Motors",
        "url": os.getenv("GENERAL_MOTORS_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Key Bank",
        "url": os.getenv("KEYBANK_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Bank of Montreal",
        "url": os.getenv("BMO_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "ASML",
        "url": os.getenv("ASML_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Voya Investments",
        "url": os.getenv("VOYA_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Aberdeen",
        "url": os.getenv("ABERDEEN_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Balyasny Asset Management",
        "url": os.getenv("BALYASNY_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Blackstone",
        "url": os.getenv("BLACKSTONE_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "CIBC",
        "url": os.getenv("CIBC_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "CBOE",
        "url": os.getenv("CBOE_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Cushman & Wakefield",
        "url": os.getenv("CUSHMAN_WAKEFIELD_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Prudential",
        "url": os.getenv("PRUDENTIAL_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Zoetis",
        "url": os.getenv("ZOETIS_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Blackrock",
        "url": os.getenv("BLACKROCK_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Travelers",
        "url": os.getenv("TRAVELERS_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Salesforce",
        "url": os.getenv("SALESFORCE_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "AIG",
        "url": os.getenv("AIG_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Genworth",
        "url": os.getenv("GENWORTH_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "CVS Health",
        "url": os.getenv("CVS_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Factset",
        "url": os.getenv("FACTSET_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Fico",
        "url": os.getenv("FICO_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Maxar",
        "url": os.getenv("MAXAR_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Nike",
        "url": os.getenv("NIKE_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Truist",
        "url": os.getenv("TRUIST_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Castleton Commodities",
        "url": os.getenv("CASTLETON_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Webster Bank",
        "url": os.getenv("WEBSTER_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Accenture",
        "url": os.getenv("ACCENTURE_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Apollo",
        "url": os.getenv("APOLLO_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Zillow",
        "url": os.getenv("ZILLOW_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Crowdstrike",
        "url": os.getenv("CROWDSTRIKE_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Fifth Third",
        "url": os.getenv("FIFTH_THIRD_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Millenium",
        "url": os.getenv("MLP_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("DEFAULT_PASSWORD"),
    },
    {
        "name": "Comcast",
        "url": os.getenv("COMCAST_URL"),
        "email": os.getenv("DEFAULT_EMAIL"),
        "password": os.getenv("COMCAST_PASSWORD"),
    },
]
